?start: query

query: "From" node "Check" property

node: "Transaction" ID
    | "Address" ID

ID: ESCAPED_STRING

property: transaction_prop
        | address_prop

transaction_prop: transaction_expression
                | "not" transaction_prop
                | transaction_prop "and" transaction_prop
                | "Maxaddr" address_atom address_prop
                | "Gtrans" INT transaction_prop
                | "Ftrans" INT transaction_prop

address_prop: address_expression
            | "not" address_prop
            | address_prop "and" address_prop
            | "Xtrans" transaction_prop
            | "Gaddr" INT address_prop
            | "Faddr" INT address_prop

transaction_expression: transaction_atom ">" transaction_atom
                    | transaction_atom "=" transaction_atom
                    | transaction_atom "<" transaction_atom

address_expression: address_atom ">" address_atom
                    | address_atom "=" address_atom
                    | address_atom "<" address_atom

transaction_atom: "Transaction." transaction_attribute
                | constant

address_atom: "Address." address_attribute
            | constant

transaction_attribute: "hash"
                    | "ver"
                    | "vin_sz"
                    | "vout_sz"
                    | "size"
                    | "weight"
                    | "fee"
                    | "relayed_by"
                    | "lock_time"
                    | "tx_index"
                    | "double_spend"
                    | "time"
                    | "block_index"
                    | "block_height"
                    | "inputs"
                    | "out"

address_attribute: "hash"
                | "address"
                | "n_tx"
                | "n_unredeemed"
                | "total_received"
                | "total_sent"
                | "final_balance"
                | "txs"

constant: INT
        | ESCAPED_STRING

%import common.INT
%import common.ESCAPED_STRING