?start: query
    
query : "From" node "Check" property

node : "Transaction" id -> transaction
        | "Address" id -> address

id : HEX
property : transaction_prop 
        | address_prop

// TRANSACTION AND ADDRESS PROPERTIES
transaction_prop : "(" transaction_prop ")"
        | transaction_expression 
        | "not" transaction_prop 
        | transaction_prop "and" transaction_prop 
        | "Maxaddr" address_atom_int address_prop 
        | "Gtrans" INT transaction_prop 
        | "Ftrans" INT transaction_prop

address_prop : "(" address_prop ")"
        | address_expression 
        | "not" address_prop 
        | address_prop "and" address_prop 
        | "Xtrans" transaction_prop 
        | "Gaddr" INT address_prop 
        | "Faddr" INT address_prop

// TODO: find a better way to handle = HEX, = IP
// TRANSACTION AND ADDRESS EXPRESSIONS
transaction_expression : transaction_atom_int ">" transaction_atom_int 
        | transaction_atom_int "=" transaction_atom_int 
        | transaction_atom_int "<" transaction_atom_int
        | transaction_atom_int ">" NUMBER 
        | transaction_atom_int "=" NUMBER
        | transaction_atom_int "<" NUMBER
        | transaction_atom_hex "=" transaction_atom_hex
        | transaction_atom_hex "=" "HEX" HEX
        | "HEX" HEX "in" transaction_atom_list
        | transaction_atom_ip "=" transaction_atom_ip
        | transaction_atom_ip "=" "IP" IP_ADDRESS
        | transaction_atom_bool "=" transaction_atom_bool
        | transaction_atom_bool "=" BOOL

address_expression : address_atom_int ">" address_atom_int 
        | address_atom_int "=" address_atom_int 
        | address_atom_int "<" address_atom_int
        | address_atom_int ">" NUMBER 
        | address_atom_int "=" NUMBER
        | address_atom_int "<" NUMBER
        | address_atom_hex "=" address_atom_hex
        | address_atom_hex "=" "HEX" HEX
        | "HEX" HEX "in" address_atom_list

// TRANSACTION AND ADDRESS ATOMS
transaction_atom_bool : "Transaction." transaction_attribute_bool
transaction_atom_hex : "Transaction." transaction_attribute_hex
transaction_atom_int : "Transaction." transaction_attribute_int
transaction_atom_list : "Transaction." transaction_attribute_list
transaction_atom_ip : "Transaction." transaction_attribute_ip

address_atom_hex : "Address." address_attribute_hex 
address_atom_int : "Address." address_attribute_int 
address_atom_list : "Address." address_attribute_list 

// TRANSACTION AND ADDRESS ATTRIBUTES
transaction_attribute_hex : "hash"

transaction_attribute_int : "ver"
        | "vin_sz"
        | "vout_sz"
        | "size"
        | "weight"
        | "fee"
        | "lock_time"
        | "tx_index"
        | "time"
        | "block_index"
        | "block_height"

transaction_attribute_bool : "double_spend"

transaction_attribute_ip : "relayed_by"

transaction_attribute_list : "inputs"
        | "out"


address_attribute_hex : "hash"
        | "address"

address_attribute_int : "n_tx"
        | "n_unredeemed"
        | "total_received"
        | "total_sent"
        | "final_balance"

address_attribute_list : "txs"

// OTHERS
HEX : ("a".."f"|"A".."F"|DIGIT)+
BOOL : "True" | "False"

IP_ADDRESS: OCTET "." OCTET "." OCTET "." OCTET
OCTET: "25" "0".."5"  // 250-255
      | "2" "0".."4" DIGIT  // 200-249
      | "1" DIGIT DIGIT  // 100-199
      | DIGIT DIGIT?

// DICT AND LIST DEFINITION
// value: dict
//         | list
//         | ESCAPED_STRING
//         | NUMBER
//         | BOOL 
//         | "None"

// list : "[" [value ("," value)*] "]"
// 
// dict : "{" [pair ("," pair)*] "}"
// pair : ESCAPED_STRING ":" value

%import common.NUMBER
%import common.ESCAPED_STRING
%import common.LETTER
%import common.DIGIT
%import common.INT
%import common.CNAME
%import common.WS_INLINE
%ignore WS_INLINE
