?start: query
    
query : "From" node "Check" property

node : "Transaction" id -> node_transaction
        | "Address" id -> node_address

id : HEX_EXT
property : transaction_prop 
        | address_prop

// TRANSACTION AND ADDRESS PROPERTIES
!transaction_prop : "(" transaction_prop ")"
        | transaction_expression 
        | "not" transaction_prop 
        | transaction_prop "and" transaction_prop 
        | "Maxaddr" address_atom address_prop 
        | "Gtrans" INT transaction_prop 
        | "Ftrans" INT transaction_prop

!address_prop : "(" address_prop ")"
        | address_expression 
        | "not" address_prop 
        | address_prop "and" address_prop 
        | "Xtrans" transaction_prop 
        | "Gaddr" INT address_prop 
        | "Faddr" INT address_prop

// TRANSACTION AND ADDRESS EXPRESSIONS
// TODO: remove transaction_atom OPERATOR transaction_atom if not needed
!transaction_expression : transaction_atom ">" transaction_atom 
        | transaction_atom "=" transaction_atom
        | transaction_atom "<" transaction_atom
        | transaction_atom ">" NUMBER 
        | transaction_atom "=" NUMBER
        | transaction_atom "<" NUMBER
        | transaction_atom "=" "HEX" HEX
        | "HEX" HEX "in" transaction_atom
        | transaction_atom "=" "IP" IP_ADDRESS
        | transaction_atom "=" BOOL

!address_expression : address_atom ">" address_atom 
        | address_atom "=" address_atom 
        | address_atom "<" address_atom
        | address_atom ">" NUMBER 
        | address_atom "=" NUMBER
        | address_atom "<" NUMBER
        | address_atom "=" "HEX" HEX_EXT
        | "HEX" HEX_EXT "in" address_atom

// TRANSACTION AND ADDRESS ATOMS
transaction_atom : "Transaction." CNAME
address_atom : "Address." CNAME 

// OTHERS
HEX : ("a".."f"|"A".."F"|DIGIT)+
HEX_EXT : ("a".."z"|"A".."Z"|DIGIT)+
BOOL : "True" | "False"

IP_ADDRESS: OCTET "." OCTET "." OCTET "." OCTET
OCTET: "25" "0".."5"  // 250-255
      | "2" "0".."4" DIGIT  // 200-249
      | "1" DIGIT DIGIT  // 100-199
      | DIGIT DIGIT?

%import common.NUMBER
%import common.DIGIT
%import common.INT
%import common.CNAME
%import common.WS_INLINE
%ignore WS_INLINE
